### PR TITLE
fix bug

### LINKED ISSUE #821: When haven't styleText the StylesheetReader will throw the exception
#### Description

image

#### Example data
``` XML
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1611709512351" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3410" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><defs><style type="text/css"></style></defs><path d="M283.21 581.7c-4.82 91.65 43.41 236.36 270.12 192.95 0 0 178.48-24.12 207.42-303.89 9.65-115.77-28.94-173.65-28.94-173.65s-241.18-67.53-356.95 57.88c-65.43 70.88-86.77 134.05-91.65 226.71z" fill="#FC597B" p-id="3411"></path><path d="M447.01 804.42c-68.38 0-122.34-21.73-163.75-65.65-40.9-43.38-63.53-103.32-60.53-160.33l17.35 0.91-17.35-0.91c2.82-53.53 10.57-94.08 25.14-131.46 15.59-40 39.27-76.41 74.52-114.6 29.57-32.03 68.74-55.3 116.44-69.17 37.36-10.86 80.02-15.98 126.79-15.23 78.9 1.27 141.87 18.67 144.51 19.41l6.2 1.74 3.57 5.36c1.77 2.66 43.27 66.52 32.88 191.22l-0.03 0.34c-7.06 68.29-23.22 128.07-48.03 177.68-20.14 40.29-46 74.01-76.84 100.23-50.88 43.24-98.6 51.75-104.67 52.68-27.17 5.17-52.55 7.78-76.2 7.78z m109.63-521.77c-40.14 0-76.61 4.71-108.51 14.04-41.36 12.09-75.08 32.02-100.22 59.26-32.21 34.89-53.71 67.83-67.68 103.65-13.17 33.78-20.2 70.99-22.82 120.67-2.51 47.72 16.6 98.06 51.12 134.67 21.35 22.65 46.14 37.83 75.78 46.42 36.53 10.59 81.18 10.96 132.71 1.09l0.94-0.15c14.77-2.14 52.51-14.57 89.1-46.27 26.89-23.3 49.54-53.35 67.32-89.34 22.48-45.52 37.21-100.71 43.78-164.04 7.71-92.9-15.54-147.07-24.13-163.51-17.91-4.35-69.51-15.54-129.76-16.42-2.54-0.05-5.09-0.07-7.63-0.07z" fill="#F2466F" p-id="3412"></path><path d="M433.23 513.44c52.6-4.27 60.63-29.28 76.06-41.48 23.63-18.68 55.8-30.1 90.85-11.11 2.67 1.45 2.97 5.23 0.62 7.17-11.48 9.47-39.7 35.57-50.71 71.23-13.97 45.26-66.24 59.45-81.97 77.26 0 0-30.02 6.9-47.39-32.66-18.17-41.4 12.54-70.41 12.54-70.41zM364.67 460.95c4.52-14.43-2.38-43.01-23.42-60.17-16.66-13.59-24.46-34.34-26.98-42.38-0.5-1.6-2.5-2.23-3.78-1.14-18.03 15.37-21.56 43.49-15.27 55.53 3.3 6.32 13.22 25.27 4.17 54.14 0 0-1.26 19.46 32.51 19.46 18.44-0.01 32.77-25.44 32.77-25.44" fill="#D4EA5A" p-id="3413"></path><path d="M287.44 486.8c-5.6 0-11.07-2.82-14.22-7.94-4.3-6.98-2.84-15.89 3.06-21.18 0.09-0.5 0.21-1.09 0.38-1.76 5.34-20.38-1.42-33.32-3.97-38.19-10.96-20.96-3.25-60.04 23.13-79.01a16.681 16.681 0 0 1 15.55-2.1c5.21 1.93 9.12 6.33 10.42 11.73 0.04 0.17 6.01 23.47 22.27 36.72 23.6 19.25 32.32 46.04 30.77 65.24 0.16 0.45 0.36 0.92 0.54 1.25 6.48 5.82 7.42 15.76 1.96 22.71-5.69 7.25-16.18 8.51-23.43 2.82-9.16-7.2-13.41-21.48-12.43-28.56 1.4-10.04-4.51-26.17-18.5-37.58-8.8-7.17-15.51-15.87-20.54-24.2-1.64 6.94-1.39 13.17-0.15 15.54 3.76 7.2 15.19 29.04 6.8 61.65-1.68 9.3-6.02 16.16-12.89 20.39a16.759 16.759 0 0 1-8.75 2.47z m21.51-22.42z m66.58-12.55z m-1.02-1c0 0.01 0.01 0.01 0 0 0.01 0.01 0 0.01 0 0z" fill="#A4E242" p-id="3414"></path><path d="M649.9 683.09c19.3-23.87 40.88-26.15 48.07-26.91 13.52-1.43 34.87-19.74 38.18-43.14 0.3-2.13-1.79-3.84-3.86-3.26-8.83 2.47-29.94 7-50.06 0.79-26.32-8.12-54.33 2.11-63.98 14.05M491.32 395.48s-17.18-25.77 17.18-85.89c28.13-49.22 10.2-81.17 2.77-91.14-1.3-1.74-3.93-1.6-5.14 0.2-32 47.61-32.6 39.81-57.76 56.59-45.76 30.51-25.77 85.89-25.77 85.89s3.87 17.17 24.13 27.78c22.3 11.68 44.59 6.57 44.59 6.57zM717.33 527.89s14.45-6.6 31.1-17.78c16.65-11.18 35.51-26.95 44.31-45.29 11.68-24.32 10.71-38.84 8.73-45.86-0.75-2.67-4.05-3.55-6.12-1.71-29.08 25.86-37.25 22.65-72.14 23.2-36.38 0.58-75.7 44.88-75.7 44.88s-10.65 23.24 17.33 38.68c21.59 11.91 52.49 3.88 52.49 3.88z" fill="#D4EA5A" p-id="3415"></path><path d="M700.22 544.54c-1.58-7.3-0.73-22.42 12.48-32.81 1.52-1.2 3.22-2.55 5.03-4.01 6.81-5.45 15.27-12.23 23.71-17.89 19.32-12.98 32.66-26.34 38.57-38.66 1.65-3.44 2.99-6.6 4.07-9.48-14.77 8.19-27.29 8.85-47.7 8.94-3.25 0.01-6.76 0.03-10.6 0.09-17.59 0.28-39.3 13.99-51.65 27.38-12.99 14.08-29.35 13.7-31.17 13.6l1.66-33.33s-0.23-0.03-0.64-0.01c0.31-0.01 3.14-0.2 5.61-2.89 15.94-17.28 45.32-37.64 75.65-38.12 3.98-0.06 7.62-0.08 10.99-0.09 12.44-0.05 19.95-0.08 26.52-2.44 6.93-2.49 14.89-8.21 27.47-19.76a16.72 16.72 0 0 1 12.69-4.33c4.65 0.39 8.92 2.72 11.78 6.4 2.92 3.76 16.4 24.74-4.61 68.5-8.61 17.93-25.45 35.39-50.05 51.92-7.27 4.88-15.14 11.18-21.46 16.24-1.9 1.52-3.67 2.94-5.27 4.19-0.2 0.16-0.3 0.27-0.32 0.3 0.01 0-0.01 0.09-0.01 0.17v-0.03c-0.02-0.08-0.16-0.95-0.16-0.95l-32.59 7.07z m87.23-128.28zM470.53 641.51c-0.2 0-0.4 0-0.61-0.01-9.21-0.33-16.41-8.06-16.08-17.27 0.69-19.45 17.24-32.79 34.76-46.91 16.21-13.07 34.58-27.87 40.61-47.39 8.69-28.15 26.58-50.7 40.92-65.29-18.33-3.97-36.88 1.37-55.39 16.01-2.28 1.8-5.21 5.43-8.32 9.28-12.17 15.06-32.54 40.28-79.69 35.72-9.17-0.88-15.89-9.04-15.01-18.21 0.89-9.17 9.04-15.89 18.21-15.01 29.27 2.82 39.6-9.95 50.53-23.48 4.12-5.1 8.38-10.37 13.58-14.48 37.11-29.34 78.2-32.5 115.69-8.86a16.67 16.67 0 0 1 7.78 13.62c0.16 5.55-2.45 10.82-6.96 14.06-0.34 0.25-37.37 27.36-49.44 66.48-9.03 29.25-32.61 48.26-51.55 63.52-7.03 5.67-13.67 11.02-18.03 15.74-4.14 4.49-4.32 6.36-4.32 6.38-0.33 9.02-7.74 16.1-16.68 16.1z" fill="#A4E242" p-id="3416"></path><path d="M477.24 783.94c18.57 0 49.52-18.57 61.9-49.52 9.75-24.39 31.04-41.09 39.63-47.07 1.75-1.22 1.76-3.89-0.03-5.06-23.5-15.32-46.72-9.14-64.36 2.61-11.52 7.68-18.57 24.76-55.71 24.76 0 0-13.03 15.42-13.86 42.1-0.96 30.88 32.43 32.18 32.43 32.18z" fill="#D4EA5A" p-id="3417"></path><path d="M471.05 794.43c-9.22 0-16.69-7.47-16.69-16.69s7.47-16.69 16.69-16.69c10.75 0 36.16-13.41 46.41-39.03 6.34-15.86 16.66-28.82 26.3-38.4-7.3-0.05-16.1 2.15-26.31 8.96-1.5 1-3.36 2.75-5.52 4.77-9.67 9.08-24.27 22.79-59.45 22.79-9.22 0-16.69-7.47-16.69-16.69s7.47-16.69 16.69-16.69c21.97 0 29.08-6.68 36.61-13.75 2.97-2.79 6.04-5.67 9.85-8.21 29.15-19.43 60.99-19.24 87.36 0.53 4.44 3.33 6.94 8.66 6.65 14.21s-3.31 10.59-8.08 13.45c-0.22 0.13-26.37 16.27-36.42 41.41-14.83 37.09-51.72 60.03-77.4 60.03zM477.44 396.15c-1.67-2.5-7.1-12.02-7.1-29.66 0-21.46 7.96-46.28 23.67-73.77 11.12-19.46 15.18-37.42 12.1-53.47-15.39 20.97-22.74 25.98-35.87 33.54-3.55 2.05-7.58 4.37-12.62 7.73-14.22 9.48-21.61 22.63-22.58 40.21-0.79 14.34 3.24 26.09 3.28 26.21 3.13 8.67-1.38 18.19-10.04 21.32-8.67 3.13-18.25-1.4-21.37-10.07-0.63-1.73-6.09-17.51-5.25-37.85 1.17-28.66 14.12-52.03 37.46-67.59 5.94-3.96 10.67-6.68 14.46-8.87 11.76-6.78 16.16-9.32 41.03-46.62 2.77-4.16 7.26-6.86 12.24-7.35 4.98-0.49 9.91 1.27 13.44 4.81 1.2 1.2 11.91 12.33 17.21 32.19 4.72 17.72 6.04 46.39-14.52 82.37-27.56 48.23-17.44 68.88-17.34 69.08-0.26-0.5-0.45-0.72-0.45-0.72l-27.75 18.51z" fill="#A4E242" p-id="3418"></path><path d="M329.84 663.59s-13.78-20.67 13.78-68.91c22.57-39.49 8.18-65.13 2.23-73.13-1.04-1.4-3.15-1.29-4.13 0.16-25.68 38.2-26.15 31.94-46.34 45.4-36.71 24.48-20.67 68.91-20.67 68.91s3.47 20.94 24.39 27.91c20.26 6.77 30.74-0.34 30.74-0.34z" fill="#D4EA5A" p-id="3419"></path><path d="M329.85 673.39c-5.39 0-10.68-2.61-13.9-7.43-3.26-4.89-17.93-32.01 13.18-86.45 6.66-11.66 10.03-22.57 10.07-32.57-9.18 11.45-15.22 15.66-24.62 21.08-2.94 1.7-5.99 3.45-9.94 6.09-10.43 6.96-15.88 16.61-16.64 29.51-0.65 10.88 2.41 19.87 2.44 19.96l-0.04-0.1-31.39 11.33c-7.08-19.62-10.53-63.36 27.11-88.46 4.86-3.24 8.7-5.45 11.79-7.23 9.2-5.3 12.3-7.09 31.82-36.38 2.77-4.16 7.26-6.86 12.24-7.35 4.98-0.49 9.91 1.27 13.44 4.81 1.49 1.49 36.19 37.25 2.69 95.88-19.99 34.98-14.45 50.76-13.87 52.21 4.44 7.57 2.25 17.38-5.15 22.31a16.657 16.657 0 0 1-9.23 2.79z m13.9-25.89l0.01 0.01c0-0.01-0.01-0.01-0.01-0.01z m-0.03-0.05c0.01 0.01 0.02 0.03 0.03 0.04-0.01-0.01-0.02-0.03-0.03-0.04zM649.89 691.44c-3.68 0-7.39-1.21-10.48-3.71-7.17-5.79-8.28-16.3-2.48-23.47 15.69-19.4 35.63-30.51 59.29-33.01 2.79-0.3 8.47-3.79 13.56-9.37-9.98 0.49-21.28-0.26-32.47-3.71-20.26-6.25-41.07 2.4-46.08 8.59-5.79 7.17-16.3 8.28-23.47 2.48-7.17-5.79-8.28-16.3-2.48-23.47 13.93-17.23 49.2-29.59 81.88-19.5 20.41 6.3 43.51-1.78 43.74-1.87 5.22-1.91 11.01-1.08 15.51 2.18 4.49 3.27 7.04 8.57 6.84 14.12-1.2 32.82-29.75 61.2-53.51 63.72-5.99 0.63-21.9 2.32-36.85 20.81a16.686 16.686 0 0 1-13 6.21z" fill="#A4E242" p-id="3420"></path><path d="M655.72 358.81s-29.38 4.81-33.34-25.87c-3.86-29.92 19.04-45.75 19.04-45.75s10.14-18.36 32.11-25.69c17.92-5.97 41.39-0.84 54.92-20.75 1.2-1.76 3.88-1.3 4.3 0.79 3.72 18.67 8.48 78.7-72.06 116.28" fill="#D4EA5A" p-id="3421"></path><path d="M654.05 381.18c-9.22 0-16.69-7.47-16.69-16.69 0-13.04 11.05-22.23 16.89-25.27 30.89-16.06 49.47-37.31 55.23-63.18 0.49-2.18 0.86-4.32 1.14-6.38-8.16 2.96-16.43 4.03-23.58 4.95-5.47 0.7-10.64 1.37-14.65 2.71-15.11 5.04-22.71 17.8-22.78 17.92-4.46 8.07-14.6 10.99-22.67 6.54-8.07-4.46-10.99-14.61-6.54-22.67 1.36-2.46 14.08-24.33 41.44-33.45 7.09-2.36 14.13-3.27 20.94-4.15 20.14-2.59 23.46-5.67 27.21-13.17 3.02-6.04 9.37-9.67 16.11-9.18 6.73 0.48 12.51 4.96 14.65 11.37 0.77 2.3 7.32 23.23 1.77 50.69-5.11 25.26-21.8 60.87-72.25 87.31-1.83 7.27-8.4 12.65-16.22 12.65z m16.68-16.68v0z" fill="#A4E242" p-id="3422"></path><path d="M240.95 675.38c0.31 4.37 0.16 8.63-0.16 13 0.29-3.97-0.23 1.1-0.34 1.65-0.42 2.13-0.95 4.24-1.57 6.32-0.62 2.08-1.32 4.14-2.14 6.15 1.19-2.92-0.44 0.76-0.88 1.62-1.98 3.88-4.35 7.5-6.98 10.96-5.73 7.52-1.42 20.46 6.46 24.63 9.5 5.02 18.51 1.57 24.63-6.46 12.33-16.2 18.44-37.59 16.99-57.86-0.67-9.37-7.8-18.46-18-18-9.18 0.4-18.73 7.93-18.01 17.99zM338.5 745.55c-10.25 0.08-20.41 0.85-30.56 2.22-12.1 1.63-22.29 4.1-29.57 14.89-5.28 7.83-1.76 20.29 6.46 24.63 9.09 4.8 19 1.9 24.63-6.46-4.1 3.36-5.13 4.43-3.08 3.21 1.14-0.63 0.79-0.47-1.06 0.48 1.32-0.11 2.88-0.67 4.2-0.89 0.41-0.07 4.97-0.71 3.2-0.48-1.15 0.16-0.7 0.11 1.35-0.15 0.94-0.11 1.87-0.21 2.81-0.3 7.19-0.73 14.4-1.08 21.62-1.13 9.41-0.07 18.44-8.23 18-18-0.44-9.72-7.91-18.1-18-18.02z" fill="#F2466F" p-id="3423"></path><path d="M248.86 706.15c0.16 2.17 0.2 4.31 0.02 6.48 0.27-3.22-0.18 0.35-0.53 1.59-0.21 0.75-2.15 4.71-0.49 1.76-0.35 0.62-3.81 6.04-1.56 3.17-5.8 7.39-7.75 18.34 0 25.46 6.48 5.95 19.25 7.91 25.46 0 8.74-11.13 14.18-24.02 13.11-38.45-0.7-9.37-7.78-18.46-18-18-9.17 0.4-18.76 7.94-18.01 17.99z" fill="#F2466F" p-id="3424"></path><path d="M312.7 727.84c-13.83-0.49-27.93 1.79-40.78 6.96-8.7 3.5-15.8 12.16-12.57 22.14 2.72 8.42 12.79 16.33 22.14 12.57 5.43-2.18 10.99-3.89 16.74-4.97 0.31-0.06 3.73-0.58 2.16-0.38-1.9 0.23 2.7-0.21 3.1-0.23 3.07-0.19 6.13-0.19 9.2-0.08 9.42 0.33 18.42-8.52 18-18-0.44-10.04-7.9-17.65-17.99-18.01z" fill="#F2466F" p-id="3425"></path></svg>

```
#### Used Versions
source code

### PR DESCRIPTION
**Pull request by BenLampson**
When haven't styleText the StylesheetReader will throw the exception #821

#### Reference Issue
Fixes #821 

#### What does this implement/fix? Explain your changes.
If haven't styletext use empty string.
``` c#
internal StylesheetReader(string styleText) : this()
{
     _reader = new StringReader(styleText??string.Empty);
    ReadCurrent();
}
```

#### Any other comments?
None

### CODE REVIEW

File: Source/External/ExCSS/StylesheetReader.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@ internal class StylesheetReader
 
         internal StylesheetReader(string styleText) : this()
         {
-            _reader = new StringReader(styleText);
+            _reader = new StringReader(styleText??string.Empty);
```
Comment (H1Gdev) [inline Source/External/ExCSS/StylesheetReader.cs:26]: @BenLampson 

Thanks for this PR !!
However, please add it to the following source file instead of this externally provided source file.
https://github.com/svg-net/SVG/blob/f631457d4127d4779c479dd980a1bbb400f9b9b7/Source/SvgDocument.cs#L490

```cs
var sheet = cssParser.Parse(cssTotal ?? string.Empty);
```

Comment (BenLampson) [reply Source/External/ExCSS/StylesheetReader.cs]: Thanks for this comment and your tips, StylesheetReader is an internal constructor, so we need not check the null case.

**Review by BenLampson — COMMENTED** [review]
fix for review content

File: Source/SvgDocument.cs [hunk 2]
```diff
@@ -487,7 +487,7 @@ private static T Open<T>(XmlReader reader) where T : SvgDocument, new()
             {
                 var cssTotal = styles.Select((s) => s.Content).Aggregate((p, c) => p + Environment.NewLine + c);
                 var cssParser = new Parser();
-                var sheet = cssParser.Parse(cssTotal);
+                var sheet = cssParser.Parse(cssTotal??string.Empty);
```
Comment (H1Gdev) [inline Source/SvgDocument.cs:490]: Please put space before and after `??`.

File: Source/External/ExCSS/StylesheetReader.cs [hunk 3]
```diff
@@ -183,4 +183,4 @@ private void BackUnsafe()
             }
         }
     }
-}
\ No newline at end of file
+}
```
Comment (H1Gdev) [inline Source/External/ExCSS/StylesheetReader.cs:186]: Please do not include this file in your PR.

Comment (BenLampson) [reply Source/External/ExCSS/StylesheetReader.cs]: fixed

**Review by BenLampson — COMMENTED** [review]
fix all space in this file

**Review by H1Gdev — APPROVED** [review]
Thanks !!
